name: Grafana
description: 'Migrated from legacy branch: terminus-platform-grafana'
featureId: grafana
domain: terminus
service: platform
phase: preplan
track: full
milestones:
  businessplan: null
  techplan: null
  finalizeplan: null
  dev-ready: null
  dev-complete: null
team:
- username: Todd Hintzmann
  role: lead
dependencies:
  depends_on: []
  depended_by: []
target_repos: []
links:
  retrospective: null
  issues: []
  pull_request: null
priority: medium
created: '2026-04-14T20:31:29Z'
updated: '2026-04-14T20:31:29Z'
phase_transitions:
- phase: preplan
  timestamp: '2026-04-14T20:31:29Z'
  user: Todd Hintzmann
docs:
  path: docs/terminus/platform/grafana
  governance_docs_path: null
migrated_from: terminus-platform-grafana
